nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  repository: gcacrapim.azurecr.io/apim-demo-app
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: apim-be-dev.gc.bartbase.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gc-bartbase
      hosts:
        - apim-be-dev.gc.bartbase.com

resources:
   limits:
     cpu: 750m
     memory: 750Mi
   requests:
     cpu: 250m
     memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 11
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85

apimPublisher:
  enable: true
  image: gcacrapim.azurecr.io/apim-publisher
  version: 4.10.1-3
  accessSecret: azure-access
  jobSleep: 30

apim:
  api_name: apim-be
  name: apim-dev-55
  resource_group: rg-apim-dev
  apiInformation: |
    {
      "properties": {
        "apiRevision": "1",
        "displayName": "APIM BE",
        "isCurrent": true,
        "path": "",
        "protocols": [
          "https"
        ],
        "serviceUrl": "https://apim-be-dev.gc.bartbase.com/",
        "subscriptionKeyParameterNames": {
          "header": "Ocp-Apim-Subscription-Key",
          "query": "subscription-key"
        },
        "subscriptionRequired": true
      }
    }
  openApiSpec: |
    openapi: 3.0.1
    info:
      title: apim-be-dev
      version: ''
    servers:
      - url: https://apim-dev-55.azure-api.net/apim-be
    paths:
      /version:
        get:
          tags:
            - api-controller
          summary: getVersion
          operationId: getVersion
          responses:
            '200':
              description: OK
              content:
                '*/*':
                  schema:
                    type: string
                  examples:
                    default:
                      value:
      /reverse-name:
        get:
          tags:
            - api-controller
          summary: reverseName
          operationId: reverseName
          parameters:
            - name: name
              in: query
              required: true
              schema:
                type: string
          responses:
            '200':
              description: OK
              content:
                '*/*':
                  schema:
                    type: string
                  examples:
                    default:
                      value:
      /health:
        get:
          tags:
            - api-controller
          summary: healthCheck
          operationId: healthCheck
          responses:
            '200':
              description: OK
              content:
                '*/*':
                  schema:
                    type: string
                  examples:
                    default:
                      value:
    components:
      securitySchemes:
        apiKeyHeader:
          type: apiKey
          name: Ocp-Apim-Subscription-Key
          in: header
        apiKeyQuery:
          type: apiKey
          name: subscription-key
          in: query
    security:
      - apiKeyHeader: [ ]
      - apiKeyQuery: [ ]    
