---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-apim"
  labels:
{{ include "apim-demo-app.labels" . | indent 4 }}
data:
  API_MANAGEMENT_SERVICE_NAME: {{ .Values.apim.name }}
  AZURE_RESOURCE_GROUP_NAME: {{ .Values.apim.resource_group }}
