# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Develop

on:
  push:
    branches:
      - develop
      - version1
      - version2
      - version3

#  pull_request:
#    branches: [ "develop" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
        cache: maven

    - name: Set version
      id: config
      run: |
        MVN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "MVN_VERSION=$(echo $MVN_VERSION)"
        VERSION="0.0.${{ github.run_number }}-dev"
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
        echo "VERSION=$(echo $VERSION)"

    - name: Show version
      run: echo ${{ env.VERSION }}

#    - name: Maven Build
#      run: mvn clean install -q

    # # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
