name: Test AKS integration # Should be renamed

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  touch_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AKS_USER_DEV }}

      - name: Get Kubeconfig
        run: |
          az aks get-credentials --resource-group apim-backend --name apim-backend-aks --file /tmp/apim-kubeconfig

      - name: Touch cluster
        run: |
          kubectl --kubeconfig /tmp/apim-kubeconfig get ns
