name: Test AKS integration # Should be renamed

on:
  pull_request:
    branches:
      - main

jobs:
  touch_cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_AKS_USER }}

      - name: Get Kubeconfig
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az aks get-credentials --resource-group apim-backend --name apim-backend-aks --file /tmp/apim-kubeconfig
      
      - name: Touch cluster
        run: |
          kubectl --kubeconfig /tmp/apim-kubeconfig get ns
